### ISSUE TITLE
Integrate timeline's method from PebbleKit Javascript

### ISSUE THREAD

**Issue by Calvein** [pebble/pebblejs#104]
The [top of the docs for Pebble.JS](http://developer.getpebble.com/docs/pebblejs/#pebble) says:

> The Pebble object from PebbleKit JavaScript is available as a global variable. Its usage is discouraged in Pebble.js, instead you should use the objects documented below who provide a cleaner object interface to the same functionalities.

The problem with this is that not everything from PebbleKit is in PebbleJS, e.g: the timelines methods.
I went around the problem by simple adding them to the timeline module:

``` js
var Timeline = require('./timeline');

Timeline.init();

// Add PebbleKit JavaScript methods to prevent to call direcly PebbleKit
Timeline.getToken = Pebble.getTimelineToken
Timeline.subscribe = Pebble.timelineSubscribe
Timeline.unsubscribe = Pebble.timelineUnsubscribe
Timeline.subscriptions = Pebble.timelineSubscriptions

module.exports = Timeline;
```

Is there a better way to do this ?

**Comment by Meiguro** [comment]
Pebble has been gaining API's faster than Pebble.js can adopt them! I should update the wording in that doc. What you are doing is perfectly fine. When no alternative is available, using the Pebble global directly is also fine since it'll be simple to search and replace when it comes time to change the code. The doc is actually attempting to encourage using the Pebble.js alternative when they exist, since they have extra functionality, such as the Settings module vs localStorage and web view.

With that said, I should eventually do as the title suggests, integrating the new timeline methods into the timeline module.
