### ISSUE TITLE
Dictation Confirmation Window Missing

### ISSUE THREAD

**Issue by mymindstorm** [pebble/pebblejs#129]
According to the [dictation API documentaion](https://developer.getpebble.com/guides/pebble-apps/sensors/dictation/) the user should be prompted with a comfirmation window after the input is read. Pebble.js dictation does not have this.

> * When the text is returned, the user is given the opportunity to review the result of the transcription. At this time they may elect to re-attempt the dictation by pressing the Back button and speaking clearer.

**Comment by Meiguro** [comment]
Note that if you use `Voice.dictate('start', false, function(e) { ... });`, there is no confirmation screen due to `false`.

Are you able to get the confirmation screen with this minimal app?

```javascript
var Voice = require('ui/voice');

Voice.dictate('start', function(e) {
  console.log(JSON.stringify(e));
});
```

It should look like this after pressing select on the microphone screen:

![pebble_screenshot_2016-02-13_21-43-30](https://cloud.githubusercontent.com/assets/4428900/13032092/e1927cd8-d29a-11e5-9607-aa01646cb2b1.png)

There could be something else preventing the confirmation window from appearing, let me know if you have any ideas.

**Comment by mymindstorm** [comment]
My bad, completely missed that! Thanks
