### ISSUE TITLE
`UnicodeDecodeError` on build

### ISSUE THREAD

**Issue by viki53** [pebble/pebblejs#138]
Hi, I think this is more related to Python, but considering I'm using the JS SDK…

I've been trying to build a basic app since yesterday and every time I get this:

```shell
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 29: ordinal not in range(128)
```

Trace show the error occurs in `/Users/corentin/Library/Application Support/Pebble SDK/SDKs/current/sdk-core/pebble/.waf-1.7.11-de6bee556e4ccb2617185d3bf23af939/waflib/Scripting.py`

I'm guessing this is due to the path of my project, that contains accents and such…

Any idea how to work around that without having to move my project?

**Comment by Meiguro** [comment]
This seems to be an issue in the base SDK caused by the json loader loading the strings as unicode and not being encoded as ascii during usage for waf environment keys.

You can work around this by inserting `ctx.all_envs = {k.encode('utf-8'): e for (k, e) in ctx.all_envs.iteritems()}` after `ctx.load` in `wscript`

The first part of wscript configure would then look like this:
```python
# ...
def configure(ctx):
    ctx.load('pebble_sdk')
    ctx.all_envs = {k.encode('utf-8'): e for (k, e) in ctx.all_envs.iteritems()}

    ctx.configure_appinfo([ctx.appinfo_bitmap_to_png])
    # ...
```

This seems to work for me. If this works for you too, be sure to contact devsupport@pebble.com to have a ticket created for this issue in case I forget to do that myself.

**Comment by viki53** [comment]
Seems to do the trick!

Now I'm getting an other error, `RuntimeError: Freetype library not found` even though I did a `brew install freetype`.  
Maybe having 2 versions installed creates a problem or I did something wrong…

**Comment by Meiguro** [comment]
One of your dependencies must have linked to freetype in the past, and your freetype installation has moved. I have had the same issue as well.

If it is looking for freetype in `/usr/local/include/freetype` but you have freetype in `/usr/local/include/freetype2`, then as a temporary solution you can symlink the directories.

```
ln -s /usr/local/include/freetype2 /usr/local/include/freetype
```

If that doesn't fix the issue, I would reinstall the package that is depending on freetype and check its build that it is linking using the right path.

**Comment by viki53** [comment]
Same error.

No I'll just have to find which package requires FreeType (knowing that it was already installed, I guess Pebble is not the only one…)

**Comment by Meiguro** [comment]
Please do report back if you find out which package you had to reinstall! I have created an internal ticket and fix for the unicode issue.
