### ISSUE TITLE
PebbleJS ajax error: send@[native code]

### ISSUE THREAD

**Issue by pshah123** [pebble/pebblejs#34]
Whenever I try to make an ajax request to google maps using a valid url (it has been tested to work in the browser) it fails and gives an error.

<h5>Code: <small>(api key removed)</small></h5>

<pre>
var directionUrl = "http://maps.googleapis.com/maps/api/directions/json?key=APIKEYHERE";
directionUrl+="&origin="+lat+","+long+"&destination=\""+placeSubtitle+"\"";
console.log(directionUrl);
ajax(
{
url: directionUrl,
type:'json'
});
</pre>

<h5>Example URL: (API KEY REMOVED)</h5>

<pre>http://maps.googleapis.com/maps/api/directions/json?key=APIKEYHERE&origin=40.79368928916826,-74.31703018031484&destination="43 South Livingston Avenue, Livingston"</pre>

<h5>Error:</h5>

<pre>send@[native code]
    at ajax (lib/ajax.js:114:11)
    at app.js:543:11
    at emitToHandlers (lib/emitter.js:121:21)
    at emit (lib/emitter.js:145:35)
    at emit (ui/window.js:273:24)
    at emit (ui/menu.js:301:14)
    at emitSelect (ui/menu.js:349:16)
    at onPacket (ui/simply-pebble.js:996:22)
</pre>

**Comment by youtux** [comment]
Have you tried `encodeURIComponent`?
```javascript
directionUrl+="&origin="+lat+","+long+"&destination="+encodeURIComponent(placeSubtitle);
```

**Comment by Meiguro** [comment]
Thanks for reporting this issue! It seems the double quotes causes the URL to be invalid on iOS. The full error is "Invalid URL" (the exception message isn't being shown, but that has been fixed). It looks like a problem with the XMLHTTPRequest object that is provided by the included iOS JavaScript VM. Other browsers, including desktop Safari, have no problem with the double quotes. I hesitate to encode the URI for the user especially since ajax has never done so, and no other xhr library does so. But I may look into doing limited encoding if it doesn't break anything that wasn't expecting encoding in the first place, for example on Android if the same URL is valid there.

In the meantime, you can use `encodeURIComponent` as youtux outlined, or `encodeURI` on the entire url before being given to `ajax`. You can also define your GET parameters in an object and use `ajax.formify` to encode them. For example:

    var params = {
      key: API_KEY,
      origin: lat + ',' + long,
      destination: '"' + placeSubtitle + '"'
    };

    ajax(
      {
        url: 'https://maps.googleapis.com/maps/api/directions/json?' + ajax.formify(params),
        type: 'json'
      },
      function success(data, status) {
         console.log('Success: ' + status);
      },
      function failure(error, status) {
         console.log('Error: ' + status + ' ' + error);
      }
    );

I changed the url to https, but I'm not sure if that works. I would hope it does.
