### ISSUE TITLE
Clock causes failure on pebble --install

### ISSUE THREAD

**Issue by mihirt** [pebble/pebblejs#40]
I recently upgraded my SDK to 3.0. I have a pebblejs app that was compiling and installing fine onto my pebble (original) with the 2.x SDK. However, with the 3.0, it compiles fine but upon installation says 
<code>Error: Cannot find module 'clock'</code>

(http://puu.sh/gKiFg/f689c6369a.png)

I thought it might be a problem with my code -- tried compiling and installing with the pebble js sample github code, and received the same error upon installation. Is there a known workaround to this?
Downgraded to 2.9, same issue.

**Comment by Meiguro** [comment]
Thanks for reporting the issue! Is your project a multi-file js project? Can you post all the invocations of require with their respective file and call order? I will try to reproduce the issue tonight.

**Comment by mihirt** [comment]
Nope, i'm just using app.js. No other js dependencies. If you'd like, my dependencies are shown [here] (http://puu.sh/gLycb/1d56781421.png). However, this issue also occurred for me when trying to build and install a clone of this repository (unmodified).

**Comment by Meiguro** [comment]
I've not been able to reproduce the issue using commit f21c51e8be018882121d21c4bf5706289c8d7133 which is tip as of now. This is not to say there is no solution, I definitely want to work with you until this problem is resolved because it's important to get rid of bugs. It just seems like this is a simple error caused by a bad non-working commit, except that I've been unable to reproduce the problem. If that's the kind of issue you're running into, I am simply missing one extra trigger condition.

In any case, thanks for trying the unmodified repository! In my experience, Android likes to aggressively cache the JavaScript. To kill the cache, unload the app from your watch. It'll be the one that appears as "Simply.js" since I've not yet fully developed the local development experience with regards to the app UUID. Use `pebble clean build` and try to install the unmodified pebble.js again.

If it's not an Android cache issue, just to be sure, is the clone also commit f21c51e8be018882121d21c4bf5706289c8d7133? As a paranoid check, you can make sure the folder and files `src/js/clock`, `src/js/clock/clock.js`, and `src/js/clock/index.js` exist. If they don't exist, there's something fishy. Chances are, they exist however.

Does the issue also occur with `pebble install --emulator=aplite --logs`? This definitely would not involve an Android cache.

Finally, try placing the code snippet `for (var path in __loader.packages) { console.log(path); }` as the first line of app.js. It will print all available packages. You should see clock.js in there. I would also like to see the full output of that in order to get a closer look at what's going on. (For posterity, __loader is undocumented because its API is not guaranteed. It should only be accessed for debugging.)

**Comment by mihirt** [comment]
Just tested this out with unloading the app. I did pebble clean then pebble build, and now the app works!
I think my problem was that I updated the Pebble app (after about 2 months), the watch software, and my SDK on the same day without reloading anything, causing Android to use the cached javascript and not locate Clock.
Also, does the emulator only run in SDK 3?

**Comment by Meiguro** [comment]
Glad it's fixed for you! Yes, the emulator was recently introduced in SDK 3.
