### ISSUE TITLE
Pebblejs not working since PebbleSDK 3.0-dp9

### ISSUE THREAD

**Issue by youtux** [pebble/pebblejs#48]
Pebblejs can't compile using PebbleSDK 3.0-dp9 because the `InverterLayer` has been removed.

**Comment by fletchto99** [comment]
Still occurs in DP 10, using the latest version of PebbleJS

**Comment by Meiguro** [comment]
I've just updated pebble.js to beta10! Let me know how it goes. Still not taking advantage of the new features, just making sure it compiles and behaves reasonably.

There are a few known issues, some of which are very tricky to solve:
- The basalt inverter layer cannot be used in combination with scrolling due to the drawing box not being exposed.
- Menu layer seems to assume that it is always position at (0, 0), so its animation is incorrect when the status bar is visible.
- Popping a window does not have an animation.

**Comment by youtux** [comment]
Great work @Meiguro!
