### ISSUE TITLE
Incorrect example for Wakeup.schedule()

### ISSUE THREAD

**Issue by scribu** [pebble/pebblejs#82]
The docs for [Wakeup.schedule](http://developer.getpebble.com/docs/pebblejs/#wakeup-schedule-options-callback-event) read:

```js
Wakeup.schedule(
  {
    // Set the wakeup event for one minute from now
    time: Date.now() / 1000 + 60,
  ...
```

But this is correct only if the timezone offset is 0. Otherwize, the wakeup will not happen after 1 minute, but after 3 hours and 1 minute, or however large the offset is.

A proper call would be:

```js
Wakeup.schedule(
  {
    // Set the wakeup event for one minute from now
    time: Date.now() / 1000 + (new Date().getTimezoneOffset() * 60) + 60,
  ...
```

**Comment by scribu** [comment]
Correction: I did get one app wakeup, but several hours late.

**Comment by marcteys** [comment]
I wanted to report the same problem.
But I'm not sure the wakeup function is working properly. I implemented a quick test here : https://gist.github.com/marcteys/a0becca8edfc27f8beb1 with your modification and the event "Launch" is never called

**Comment by scribu** [comment]
I get a different behavior:

```js
function schedule() {
	var now = Date.now() / 1000 + (new Date().getTimezoneOffset() * 60);
	// var now = Date.now() / 1000;
	var time = now + 60;

	Wakeup.schedule({time: time}, onScheduleSet);
}

schedule();  // works

main.on('click', 'down', schedule);  // invalidArgument error
```

> [Edit] : I am using cloudpebble, and there might be Date-related problem relative to their server location !?

I get the same behavior on the Basalt emulator as on a real Pebble Time.

**Comment by marcteys** [comment]
Scheduling a wakeup seems to work but they never launch events (even your demo)

**Comment by scribu** [comment]
Since we're both running the same software (CloudPebble + Basalt Emulator + demo app), logic would dictate that the only possible source for the difference in behavior is the timezone, like you initially suggested.

For me, `console.log(Date())` returns something like this on the emulator:

```
Sun Jul 26 2015 16:38:52 GMT+0300 (PBL)
```

On the real Pebble time, it looks like this:

```
Sun Jul 26 2015 16:38:52 GMT+0300 (EEST)
```

What does it look like for you?

**Comment by marcteys** [comment]
On the emulator I have `Sun Jul 26 2015 18:14:45 GMT-0400 (PBL)` , and on the real pebble : `Sun Jul 26 2015 18:14:45 GMT-0400 (EDT)`. Same thing here. Wakeup are set but never launch.
I think the Wakeup function is broken

**Comment by nschulte** [comment]
+1 I'm having these issues as well. Timing doesn't work as described in the docs and I can't get anything to wakeup.

**Comment by Meiguro** [comment]
My apologies, the issue a race condition with pebble.js deciding whether it needs to adjust for non-timezone enabled Pebbles. That is, during startup, it is waiting for the watch to respond whether it has timezones on or not. The race condition exists because I did not want to block all startup application logic just for the Wakeup API. The fix now correctly asynchronously schedules the wakeup event, while keeping all other startup logic starting as early as possible just as before.

If you've adjusted using `(new Date().getTimezoneOffset() * 60)`, you'll no longer need to do so if the schedule is happening immediately at startup. For any wakeup after startup, such as via a user's button press, there should have not needed any offset adjustments, unless there is another bug that should be reported.

For those that build with the local SDK, let me know how it goes. If everything is good, I'll schedule it to be updated on CloudPebble.

**Comment by scribu** [comment]
Seems to work as expected. Thanks!

**Comment by marcteys** [comment]
@Meiguro Do you think you can push this commit to cloudpebble ? It seems that you're the only one allowed to do that ;)

**Comment by Meiguro** [comment]
Sure, I'll make a request tomorrow afternoon since there seems be another issue involving pushing dynamic windows.

**Comment by marcteys** [comment]
Thanks for the merge request!
It's still not working yet on cloudpebble.net though.

**Comment by Meiguro** [comment]
I just checked and the update seems to be applied to CloudPebble, did you try recompiling your app?

**Comment by marcteys** [comment]
Hum, I tried with this exemple and it's not working. 
https://gist.github.com/marcteys/a0becca8edfc27f8beb1
Event are scheduled but never launched. Is it working for you ?

**Comment by Meiguro** [comment]
Thanks for posting a gist, I've replied in the gist directly. There was an extra `(new Date().getTimezoneOffset() * 60)`. Let me know how it goes.

**Comment by marcteys** [comment]
I updated the gist, still not working. I try to debug Dates and schedules but I really couldn't see why events are not launching.

**Comment by Meiguro** [comment]
Are you exiting the app before the wakeup time? Right now, Wakeup.launch will only fire an event once and only immediately after launch. I plan to add an API such as `Wakeup.on('wakeup', ...)` that will receive events even while the app is already running.

**Comment by marcteys** [comment]
I am not exiting the app at all. 
So the wakeup cannot be launched if the user is actually on the app ? If yes the "problem" definitely come from here, and I think on the doc, the part `[...]Whether the user is in a watchface or in a different app[...]` should be changed  by `[...]Whether the user is in a different watchface or app[...]`. 

I wanted to try to schedule some automatic data refresh : because SetTimeout is not recommanded, I don't know what is the best way to create this behavior.

**Comment by Meiguro** [comment]
That is interesting, I had written that part subconsciously not taking into account pebble.js watchfaces. Thanks for pointing that out. That part of the doc refers to launching your app which is not possible or necessary if the app is already launched however. I'll definitely touch up the wording there after implementing the missing Wakeup event handler feature.

Regarding setTimeout, you are welcome to use it. In fact, using the Wakeup API as a replacement can be detrimental depending on the use case since that reads and writes to the watch's flash. The Wakeup API is more for launching your app when it must perform something regardless of whether it was previously running or not. setTimeout is often discouraged in order to have our developers be aware of the power issues it can cause. It is however not banned from use. Examples of discouraged uses of setTimeout is constantly running something every 10 milliseconds or 100 milliseconds. setTimeout with less than one second timeouts are also not completely discouraged; for timing sensitive procedures that do not continuously run it is perfectly fine.

If however you need constant realtime data, it is understandable to have a setTimeout or setInterval that runs every minute. I recommend to try intervals of 5 minutes, 10 minutes, or 15 minutes. Information at a glance usually means the user is looking away most of the time, glancing every so often. Though if the actual use case requires glancing more than every 5 minutes, then you are free to try one minute intervals as long as you check your new total watch and phone battery life. In the end, it is the battery benchmark that should guide your decision of what you should do.

For your particular use case, it sounds like you should use setInterval with an interval in the minutes.

**Comment by marcteys** [comment]
Thanks for this advice. That's an interesting though.
 I wanted to use the interval in minutes so it will be fine for this time.

---

I really wish I could help you on this project, but I took two day trying to set up the environment without success. I would loved to work on this problem as well as the aggressive "disconnected" behavior. The amount and quality of your work here is exceptional, I definitely think that pebblejs deserve more attention.

**Comment by Meiguro** [comment]
Thanks for your kind words! I'm also sorry I haven't been working on making the "disconnected" experience better. Lately I have been making windows on basalt stop crashing in edge cases, but I'll get to it eventually!

Closing this as it seems to be resolved. Feel free to open another ticket when any new Wakeup issues.
