### ISSUE TITLE
PebbleJS and setTimeout

### ISSUE THREAD

**Issue by marcteys** [pebble/pebblejs#85]
Hi,

I try to do some call between two modules in PebbleJS, following this example : 
https://gist.github.com/marcteys/00a6b554e82b79e1645f

I don't know if it's a JS problem or a PebbleJS problem, but when I hit play I have this error : 
'TypeError: Cannot read property 'apply' of undefined
    at pebble-js-app.js:875:16 '

I have been working all the day on this few lines and I can't solve the problem. Any ideas ?

**Comment by Meiguro** [comment]
In your two modules, `this.exports` should be `module.exports`. `this` should not be trusted in global scope.

The error, while harmful sounding, does not cause pebble.js to behave different from regular JavaScript, but is essentially complaining that an undefined value was passed to `setTimeout` (caused by setting `exports` of `this` instead of `module`). There was a recent change to fix it to show a more helpful warning.

**Comment by marcteys** [comment]
Thanks for these details.
I've got the same error with module.exports, though.

**Comment by Meiguro** [comment]
Ah, you also have the issue of a cyclic dependency since both modules require each other. When there is a cyclic dependency, the last module will execute before all other modules have completed loading.

In this case, rather than doing:
```
var NewObject = {
   myFunction: function() {}
};
module.exports = NewObject;
```

You would instead use the object provided by `module.exports`
```
var MyModule = module.exports;
MyModule.myFunction = function() {};
```

This is because the object provided by `module.exports` is what will be given to the last module that tries to load modules that are not completely done loading. When you do `module.exports = MyModule`, that changes the object that needs to be referenced as the module. `module.exports = MyModule` is perfectly fine for modules that are not part of cyclic dependencies.

Once both App and Other are changed to this, Other will run with an App that has nothing in it, but once Other is done loading, `App.event` will become defined `App.init` will run, and `Other.delayFunction` will be able to reference the function `App.event` which was previously undefined during `Other`'s initialization.

This is a general issue for CommonJS module implementations, and not specific to pebble.js.

**Comment by marcteys** [comment]
Thank you for you explanations @Meiguro, you're definitely a good teacher.
I changed my design pattern to follow a non-cyclic method as you mentioned, everything is working fine now !

**Comment by marcteys** [comment]
Well, after some user tests, we found out that setTimeout sometimes doesn't work. It's impossible to debut because it happens totally randomly, sometimes after few hours, sometimes after few minutes. 
It's probably because of the JS on the phone. I think the only solution I can imagine is to use a kind of [TickTimer](http://developer.getpebble.com/docs/c/Foundation/Event_Service/TickTimerService/) event system.

**Comment by Meiguro** [comment]
What are you sending over to the watch? Is it data fetched from the internet?

**Comment by marcteys** [comment]
The system is a little bit more complicated, I have some "internal" Timeout (modifications only localy) and some "external" (fetched from internet).
Everything is working fine 95% of the time, but sometimes it breaks, and I'm almost sure that my code is correct (I clear the variables, etc ). 
I just wanted to share that with you, I guess it's not very urgent to find a solution because this problem is very hard to debug. And there will probably be in the some a proper way to do that with pebbleJS. 
[Full project](https://github.com/marcteys/pebble-dayline) (you're now collaborator, before I make it public )

**Comment by Meiguro** [comment]
Thanks for the source access! That's always important for reproducing the issue. Since it's data from the internet, I'll investigate why setTimeout is failing. Do you know if your users with the issue are on Android, iOS, or both? Do you experience the issue yourself? It is entirely possible we are looking into the general issue of keeping PebbleKit JS alive, which is nontrivial and is a combination of many factors, so the extra context is helpful.

**Comment by marcteys** [comment]
You're welcome, it will be easier for you. If you want you can publish commit if it's easier for you.
My users are on Android, I had this issue at least once, because it didn't refresh this night. 
I have made a test where I fetch data from internet from my phone (Android) every 5 seconds during 20 minutes, everything was working fine. 

Basically this app has two kind of refresh, on external to get Google Calendar and weather data. The "internal" one is used to refresh the timebar position (current time ) and to display the next event detail.
