### ISSUE TITLE
PTR (chalk) support

### ISSUE THREAD

**Issue by technoboy10** [pebble/pebblejs#96]
This is clearly a non-essential enhancement, but it would be nice if PebbleJS could support the new Time Round watch.

**Comment by kinncj** [comment]
https://github.com/pebble/pebblejs/commit/f67c19adaaa96b1071f2e64f03a0983aeed05844

**Comment by elvquant** [comment]
And integration into "CloudPebble.net". Pebble.js cannot run on chalk emulator (Button disabled)

**Comment by eevleevs** [comment]
Essential here

**Comment by nguyer** [comment]
Hey, any update on this? What is still missing, and can I help with any part of it? I have one or two pebble.js apps that I'd like to run on the Pebble Time Round.

**Comment by daduke** [comment]
Hi,

I didn't check Cloudpebble, but using the SDK I managed to come up with a halfway decent chalk Pebble.js app: https://apps.getpebble.com/en_US/application/565c94c0eae744b790000068

cheers,
-Christian

**Comment by technoboy10** [comment]
Can also confirm - I've built two apps with pebble.js that support chalk perfectly (not on cloudpebble for some reason, but building offline works great).

**Comment by Meiguro** [comment]
Thanks @daduke and @technoboy10! I've been slowly adding Chalk support, it's great to know it's been working well for you two. There's nothing wrong with CloudPebble -- it just doesn't yet have the latest version of pebble.js yet because I would like to update the docs with all the changes and have those both up at the same time. I'll be sure to update this ticket when that's done.

**Comment by Meiguro** [comment]
Finally merged on CloudPebble! Thanks everyone.
